// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ5e8okf_gbC2y7qNSv5jhsJZS0KdnYy0',
    appId: '1:515030965730:web:3612d6a22557770a052dbb',
    messagingSenderId: '515030965730',
    projectId: 'deep-links-3deec',
    authDomain: 'deep-links-3deec.firebaseapp.com',
    storageBucket: 'deep-links-3deec.firebasestorage.app',
    measurementId: 'G-QJ3WNY35KP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_u_uGELir64gnauYyeKgsKAo-8SzYcBA',
    appId: '1:515030965730:android:bda98a00e46ae515052dbb',
    messagingSenderId: '515030965730',
    projectId: 'deep-links-3deec',
    storageBucket: 'deep-links-3deec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoUws-A_3PrmbLl_uyLxXqS6saMfGwv-Q',
    appId: '1:515030965730:ios:ae988b0fb23345e7052dbb',
    messagingSenderId: '515030965730',
    projectId: 'deep-links-3deec',
    storageBucket: 'deep-links-3deec.firebasestorage.app',
    iosBundleId: 'com.example.deepLinks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoUws-A_3PrmbLl_uyLxXqS6saMfGwv-Q',
    appId: '1:515030965730:ios:ae988b0fb23345e7052dbb',
    messagingSenderId: '515030965730',
    projectId: 'deep-links-3deec',
    storageBucket: 'deep-links-3deec.firebasestorage.app',
    iosBundleId: 'com.example.deepLinks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ5e8okf_gbC2y7qNSv5jhsJZS0KdnYy0',
    appId: '1:515030965730:web:32c63bdeee28d001052dbb',
    messagingSenderId: '515030965730',
    projectId: 'deep-links-3deec',
    authDomain: 'deep-links-3deec.firebaseapp.com',
    storageBucket: 'deep-links-3deec.firebasestorage.app',
    measurementId: 'G-XZ5VRYPSNR',
  );
}
